apiVersion: apps/v1
kind: Deployment
metadata:
  name: gojenkins2024
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gojenkins2024
  template:
    metadata:
      labels:
        app: gojenkins2024
    spec:
      containers:
      - name: gojenkins2024
        image: gojenkins2024:latest
        ports:
        - containerPort: 8080
        